"""drift check

Revision ID: 354ee358430f
Revises: dc26c5dd058e
Create Date: 2026-09-07 23:41:53.956108

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '354ee358430f'
down_revision: str | None = 'dc26c5dd058e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
