"""drift check after accounts

Revision ID: 590a8f4301ad
Revises: 354ee358430f
Create Date: 2026-09-08 00:11:52.041382

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '590a8f4301ad'
down_revision: str | None = '354ee358430f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
