"""accounts, presets and visits

Revision ID: dc26c5dd058e
Revises: 
Create Date: 2026-09-07 23:41:42.780692

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'dc26c5dd058e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('consent', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_address'), 'visits', ['address'], unique=False)
    op.create_index(op.f('ix_visits_created'), 'visits', ['created'], unique=False)
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logins_token'), 'logins', ['token'], unique=True)
    op.create_index(op.f('ix_logins_user_id'), 'logins', ['user_id'], unique=False)
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=22), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_owner_id'), 'presets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_presets_slug'), 'presets', ['slug'], unique=True)
    op.create_index(op.f('ix_presets_system'), 'presets', ['system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presets_system'), table_name='presets')
    op.drop_index(op.f('ix_presets_slug'), table_name='presets')
    op.drop_index(op.f('ix_presets_owner_id'), table_name='presets')
    op.drop_table('presets')
    op.drop_index(op.f('ix_logins_user_id'), table_name='logins')
    op.drop_index(op.f('ix_logins_token'), table_name='logins')
    op.drop_table('logins')
    op.drop_index(op.f('ix_visits_created'), table_name='visits')
    op.drop_index(op.f('ix_visits_address'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
