/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TopicsFractalsIndexRouteImport } from './routes/topics/fractals/index'
import { Route as TopicsFractalsPartsRouteImport } from './routes/topics/fractals/parts'
import { Route as TopicsFractalsTheoryRouteImport } from './routes/topics/fractals/theory'
import { Route as TopicsFractalsPlayIndexRouteImport } from './routes/topics/fractals/play/index'
import { Route as TopicsFractalsPlaySystemRouteImport } from './routes/topics/fractals/play/$system'
import { Route as TopicsFractalsPlayDlaRouteImport } from './routes/topics/fractals/play/dla'
import { Route as TopicsFractalsPlayIfsRouteImport } from './routes/topics/fractals/play/ifs'
import { Route as TopicsFractalsPlayJuliaRouteImport } from './routes/topics/fractals/play/julia'
import { Route as TopicsFractalsPlayLichtenbergRouteImport } from './routes/topics/fractals/play/lichtenberg'
import { Route as TopicsFractalsPlayLsystemRouteImport } from './routes/topics/fractals/play/lsystem'
import { Route as TopicsFractalsPlayMandelbrotRouteImport } from './routes/topics/fractals/play/mandelbrot'
import { Route as TopicsFractalsPlayMandelbulbRouteImport } from './routes/topics/fractals/play/mandelbulb'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsIndexRoute = TopicsFractalsIndexRouteImport.update({
  id: '/topics/fractals/',
  path: '/topics/fractals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPartsRoute = TopicsFractalsPartsRouteImport.update({
  id: '/topics/fractals/parts',
  path: '/topics/fractals/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsTheoryRoute = TopicsFractalsTheoryRouteImport.update({
  id: '/topics/fractals/theory',
  path: '/topics/fractals/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPlayIndexRoute = TopicsFractalsPlayIndexRouteImport.update({
  id: '/topics/fractals/play/',
  path: '/topics/fractals/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPlaySystemRoute =
  TopicsFractalsPlaySystemRouteImport.update({
    id: '/topics/fractals/play/$system',
    path: '/topics/fractals/play/$system',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicsFractalsPlayDlaRoute = TopicsFractalsPlayDlaRouteImport.update({
  id: '/topics/fractals/play/dla',
  path: '/topics/fractals/play/dla',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPlayIfsRoute = TopicsFractalsPlayIfsRouteImport.update({
  id: '/topics/fractals/play/ifs',
  path: '/topics/fractals/play/ifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPlayJuliaRoute = TopicsFractalsPlayJuliaRouteImport.update({
  id: '/topics/fractals/play/julia',
  path: '/topics/fractals/play/julia',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFractalsPlayLichtenbergRoute =
  TopicsFractalsPlayLichtenbergRouteImport.update({
    id: '/topics/fractals/play/lichtenberg',
    path: '/topics/fractals/play/lichtenberg',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicsFractalsPlayLsystemRoute =
  TopicsFractalsPlayLsystemRouteImport.update({
    id: '/topics/fractals/play/lsystem',
    path: '/topics/fractals/play/lsystem',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicsFractalsPlayMandelbrotRoute =
  TopicsFractalsPlayMandelbrotRouteImport.update({
    id: '/topics/fractals/play/mandelbrot',
    path: '/topics/fractals/play/mandelbrot',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopicsFractalsPlayMandelbulbRoute =
  TopicsFractalsPlayMandelbulbRouteImport.update({
    id: '/topics/fractals/play/mandelbulb',
    path: '/topics/fractals/play/mandelbulb',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/fractals/parts': typeof TopicsFractalsPartsRoute
  '/topics/fractals/theory': typeof TopicsFractalsTheoryRoute
  '/topics/fractals/': typeof TopicsFractalsIndexRoute
  '/topics/fractals/play/$system': typeof TopicsFractalsPlaySystemRoute
  '/topics/fractals/play/dla': typeof TopicsFractalsPlayDlaRoute
  '/topics/fractals/play/ifs': typeof TopicsFractalsPlayIfsRoute
  '/topics/fractals/play/julia': typeof TopicsFractalsPlayJuliaRoute
  '/topics/fractals/play/lichtenberg': typeof TopicsFractalsPlayLichtenbergRoute
  '/topics/fractals/play/lsystem': typeof TopicsFractalsPlayLsystemRoute
  '/topics/fractals/play/mandelbrot': typeof TopicsFractalsPlayMandelbrotRoute
  '/topics/fractals/play/mandelbulb': typeof TopicsFractalsPlayMandelbulbRoute
  '/topics/fractals/play/': typeof TopicsFractalsPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/fractals/parts': typeof TopicsFractalsPartsRoute
  '/topics/fractals/theory': typeof TopicsFractalsTheoryRoute
  '/topics/fractals': typeof TopicsFractalsIndexRoute
  '/topics/fractals/play/$system': typeof TopicsFractalsPlaySystemRoute
  '/topics/fractals/play/dla': typeof TopicsFractalsPlayDlaRoute
  '/topics/fractals/play/ifs': typeof TopicsFractalsPlayIfsRoute
  '/topics/fractals/play/julia': typeof TopicsFractalsPlayJuliaRoute
  '/topics/fractals/play/lichtenberg': typeof TopicsFractalsPlayLichtenbergRoute
  '/topics/fractals/play/lsystem': typeof TopicsFractalsPlayLsystemRoute
  '/topics/fractals/play/mandelbrot': typeof TopicsFractalsPlayMandelbrotRoute
  '/topics/fractals/play/mandelbulb': typeof TopicsFractalsPlayMandelbulbRoute
  '/topics/fractals/play': typeof TopicsFractalsPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/fractals/parts': typeof TopicsFractalsPartsRoute
  '/topics/fractals/theory': typeof TopicsFractalsTheoryRoute
  '/topics/fractals/': typeof TopicsFractalsIndexRoute
  '/topics/fractals/play/$system': typeof TopicsFractalsPlaySystemRoute
  '/topics/fractals/play/dla': typeof TopicsFractalsPlayDlaRoute
  '/topics/fractals/play/ifs': typeof TopicsFractalsPlayIfsRoute
  '/topics/fractals/play/julia': typeof TopicsFractalsPlayJuliaRoute
  '/topics/fractals/play/lichtenberg': typeof TopicsFractalsPlayLichtenbergRoute
  '/topics/fractals/play/lsystem': typeof TopicsFractalsPlayLsystemRoute
  '/topics/fractals/play/mandelbrot': typeof TopicsFractalsPlayMandelbrotRoute
  '/topics/fractals/play/mandelbulb': typeof TopicsFractalsPlayMandelbulbRoute
  '/topics/fractals/play/': typeof TopicsFractalsPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/topics/'
    | '/topics/fractals/parts'
    | '/topics/fractals/theory'
    | '/topics/fractals/'
    | '/topics/fractals/play/$system'
    | '/topics/fractals/play/dla'
    | '/topics/fractals/play/ifs'
    | '/topics/fractals/play/julia'
    | '/topics/fractals/play/lichtenberg'
    | '/topics/fractals/play/lsystem'
    | '/topics/fractals/play/mandelbrot'
    | '/topics/fractals/play/mandelbulb'
    | '/topics/fractals/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/topics'
    | '/topics/fractals/parts'
    | '/topics/fractals/theory'
    | '/topics/fractals'
    | '/topics/fractals/play/$system'
    | '/topics/fractals/play/dla'
    | '/topics/fractals/play/ifs'
    | '/topics/fractals/play/julia'
    | '/topics/fractals/play/lichtenberg'
    | '/topics/fractals/play/lsystem'
    | '/topics/fractals/play/mandelbrot'
    | '/topics/fractals/play/mandelbulb'
    | '/topics/fractals/play'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/topics/'
    | '/topics/fractals/parts'
    | '/topics/fractals/theory'
    | '/topics/fractals/'
    | '/topics/fractals/play/$system'
    | '/topics/fractals/play/dla'
    | '/topics/fractals/play/ifs'
    | '/topics/fractals/play/julia'
    | '/topics/fractals/play/lichtenberg'
    | '/topics/fractals/play/lsystem'
    | '/topics/fractals/play/mandelbrot'
    | '/topics/fractals/play/mandelbulb'
    | '/topics/fractals/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TopicsFractalsPartsRoute: typeof TopicsFractalsPartsRoute
  TopicsFractalsTheoryRoute: typeof TopicsFractalsTheoryRoute
  TopicsFractalsIndexRoute: typeof TopicsFractalsIndexRoute
  TopicsFractalsPlaySystemRoute: typeof TopicsFractalsPlaySystemRoute
  TopicsFractalsPlayDlaRoute: typeof TopicsFractalsPlayDlaRoute
  TopicsFractalsPlayIfsRoute: typeof TopicsFractalsPlayIfsRoute
  TopicsFractalsPlayJuliaRoute: typeof TopicsFractalsPlayJuliaRoute
  TopicsFractalsPlayLichtenbergRoute: typeof TopicsFractalsPlayLichtenbergRoute
  TopicsFractalsPlayLsystemRoute: typeof TopicsFractalsPlayLsystemRoute
  TopicsFractalsPlayMandelbrotRoute: typeof TopicsFractalsPlayMandelbrotRoute
  TopicsFractalsPlayMandelbulbRoute: typeof TopicsFractalsPlayMandelbulbRoute
  TopicsFractalsPlayIndexRoute: typeof TopicsFractalsPlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/': {
      id: '/topics/fractals/'
      path: '/topics/fractals'
      fullPath: '/topics/fractals/'
      preLoaderRoute: typeof TopicsFractalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/parts': {
      id: '/topics/fractals/parts'
      path: '/topics/fractals/parts'
      fullPath: '/topics/fractals/parts'
      preLoaderRoute: typeof TopicsFractalsPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/theory': {
      id: '/topics/fractals/theory'
      path: '/topics/fractals/theory'
      fullPath: '/topics/fractals/theory'
      preLoaderRoute: typeof TopicsFractalsTheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/': {
      id: '/topics/fractals/play/'
      path: '/topics/fractals/play'
      fullPath: '/topics/fractals/play/'
      preLoaderRoute: typeof TopicsFractalsPlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/$system': {
      id: '/topics/fractals/play/$system'
      path: '/topics/fractals/play/$system'
      fullPath: '/topics/fractals/play/$system'
      preLoaderRoute: typeof TopicsFractalsPlaySystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/dla': {
      id: '/topics/fractals/play/dla'
      path: '/topics/fractals/play/dla'
      fullPath: '/topics/fractals/play/dla'
      preLoaderRoute: typeof TopicsFractalsPlayDlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/ifs': {
      id: '/topics/fractals/play/ifs'
      path: '/topics/fractals/play/ifs'
      fullPath: '/topics/fractals/play/ifs'
      preLoaderRoute: typeof TopicsFractalsPlayIfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/julia': {
      id: '/topics/fractals/play/julia'
      path: '/topics/fractals/play/julia'
      fullPath: '/topics/fractals/play/julia'
      preLoaderRoute: typeof TopicsFractalsPlayJuliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/lichtenberg': {
      id: '/topics/fractals/play/lichtenberg'
      path: '/topics/fractals/play/lichtenberg'
      fullPath: '/topics/fractals/play/lichtenberg'
      preLoaderRoute: typeof TopicsFractalsPlayLichtenbergRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/lsystem': {
      id: '/topics/fractals/play/lsystem'
      path: '/topics/fractals/play/lsystem'
      fullPath: '/topics/fractals/play/lsystem'
      preLoaderRoute: typeof TopicsFractalsPlayLsystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/mandelbrot': {
      id: '/topics/fractals/play/mandelbrot'
      path: '/topics/fractals/play/mandelbrot'
      fullPath: '/topics/fractals/play/mandelbrot'
      preLoaderRoute: typeof TopicsFractalsPlayMandelbrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/fractals/play/mandelbulb': {
      id: '/topics/fractals/play/mandelbulb'
      path: '/topics/fractals/play/mandelbulb'
      fullPath: '/topics/fractals/play/mandelbulb'
      preLoaderRoute: typeof TopicsFractalsPlayMandelbulbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TopicsFractalsPartsRoute: TopicsFractalsPartsRoute,
  TopicsFractalsTheoryRoute: TopicsFractalsTheoryRoute,
  TopicsFractalsIndexRoute: TopicsFractalsIndexRoute,
  TopicsFractalsPlaySystemRoute: TopicsFractalsPlaySystemRoute,
  TopicsFractalsPlayDlaRoute: TopicsFractalsPlayDlaRoute,
  TopicsFractalsPlayIfsRoute: TopicsFractalsPlayIfsRoute,
  TopicsFractalsPlayJuliaRoute: TopicsFractalsPlayJuliaRoute,
  TopicsFractalsPlayLichtenbergRoute: TopicsFractalsPlayLichtenbergRoute,
  TopicsFractalsPlayLsystemRoute: TopicsFractalsPlayLsystemRoute,
  TopicsFractalsPlayMandelbrotRoute: TopicsFractalsPlayMandelbrotRoute,
  TopicsFractalsPlayMandelbulbRoute: TopicsFractalsPlayMandelbulbRoute,
  TopicsFractalsPlayIndexRoute: TopicsFractalsPlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
